
title: pwkbb
#email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Personal Website and Knowledge Base (created and saved as a Blog)

url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog

# theme: minima

plugins:
  - jekyll-feed

#
# Generate social links in footer.

social_links:
  - { platform: linkedin,       user_url: "https://www.linkedin.com/in/jekyll" }
  - { platform: github,         user_url: "https://github.com/jekyll/minima" }
  - { platform: twitter,        user_url: "https://twitter.com/jekyllrb" }

# The following are not implemented yet.
#  - { platform: devto,          user_url: "https://dev.to/jekyll" }
#  - { platform: dribbble,       user_url: "https://dribbble.com/jekyll" }
#  - { platform: facebook,       user_url: "https://www.facebook.com/jekyll" }
#  - { platform: flickr,         user_url: "https://www.flickr.com/photos/jekyll" }
#  - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=qc6CJjYAAAAJ" }
#  - { platform: instagram,      user_url: "https://www.instagram.com/jekyll" }
#  - { platform: keybase,        user_url: "https://keybase.io/jekyll" }
#  - { platform: microdotblog,   user_url: "https://micro.blog/jekyll" }
#  - { platform: pinterest,      user_url: "https://www.pinterest.com/jekyll" }
#  - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/1234567/jekyll" }
#  - { platform: telegram,       user_url: "https://t.me/jekyll" }
#  - { platform: youtube,        user_url: "https://www.youtube.com/jekyll" }

#
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
